FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Polls

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/search]


## Search guides [/guide/{customerid}{?locationlt,locationlg,duration}]

+ Parameters
    + customerid - A path variable that is required for a valid URL
    + locationlt  - A query variable
    + locationlg - Another query variable
    + duration - Another query variable

### Get Available Guides [GET]

+ Response 200 (application/json)

        [
            {
                "firstName": "Akram",
                "Lastname": "Melice",
                "rating": -5,
                "profileimg":"https://hostedimage@noidea.com"
            },
            {
                "firstName": "Islam",
                "Lastname": "Elmenshawy",
                "rating": 100,
                "profileimg":"https://hostedimage@noidea.com"
            }
        ]
        
## Trip Cost Estimator [/estimate{?locationlt,locationlg,duration}]

+ Parameters
    + customerid - A path variable that is required for a valid URL
    + locationlt  - A query variable
    + locationlg - Another query variable
    + duration - Another query variable

### Get Trip Estimate [GET]

+ Response 200 (application/json)

        {
            "CostAmount": 5.5,
            "Currency" : "usd"
        }

## Statements [/statements{?locationlt,locationlg,duration}]

+ Parameters
    + locationlt  - A query variable
    + locationlg - Another query variable
    + duration - Another query variable

### Get Trip Estimate [GET]

+ Response 200 (application/json)

       [
            {
              "id": 1,
              "make": "08/01/2019",
              "model": "Model 3",
              "price": 35000,
              "status": "processed"
            },
            {
              "id": 2,
              "make": "08/01/2019",
              "model": "Model z",
              "price": 32000,
              "status": "partially processed"
            }
         ]